- name: Reading secrets from vault
  hosts: localhost
  tasks:
    - name: Connect to vault using Tools
      ansible.builtin.debug:
        msg: "PSW is {{secrets.MYSQL_PASS}}"
      vars:
        secrets: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=expense-dev/data/backend', token=token, url='https://vault.devsecopswithshri.site:8200', validate_certs=False) }}"


#To get the secrets from hashi vault, you need to install "pip3.11 install hvac" on host where you are running this playbook

#command to run this playbook
# ansible-playbook 012-ReadSecretsFromVault.yml -e token="providethe token here"       